# Generated by Django 5.2.3 on 2025-06-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizer',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_phone_number', violation_error_message='That phone number is already in use!'),
        ),
    ]
