# Generated by Django 5.2.3 on 2025-06-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_organizer_unique_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizer',
            name='unique_phone_number',
        ),
    ]
