# Generated by Django 5.2.3 on 2025-06-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-start_time']},
        ),
    ]
