# Generated by Django 5.1.1 on 2024-09-19 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Album Name')),
                ('artist_name', models.CharField(max_length=30, verbose_name='Artist')),
                ('genre', models.CharField(choices=[('Pop Music', 'Genre Pop'), ('Jazz Music', 'Genre Jazz'), ('Rock Music', 'Genre Rock'), ('Country Music', 'Genre Country'), ('R&B Music', 'Genre Rnb'), ('Dance Music', 'Genre Dance'), ('Hip Hop Music', 'Genre Hip Hop'), ('Other', 'Genre Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.profile')),
            ],
        ),
    ]
