# Generated by Django 5.2.3 on 2025-06-19 16:17

import django.core.validators
import traveler.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Nicknames can contain only letters and digits.', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), traveler.validators.NicknameValidator()])),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('country', models.CharField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
