# Generated by Django 5.1 on 2024-08-26 09:06

import django.core.validators
import forms_advanced.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, validators=[forms_advanced.web.models.validate_first_name, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
